# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET lambda build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  ZIP_PATH: /AWSLambda/AWSLambda/bin/Release/net6.0/${{ github.run_id }}.zip
  DLL_PATH: /AWSLambda/AWSLambda/bin/Release/net6.0/AWSLambda.dll
            #/home/runner/work/AWSLambda/AWSLambda/bin/Release/net6.0/AWSLambda.dll

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
        
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build -c Release --no-restore

    - name: Create Zip File
      uses: papeloto/action-zip@v1
      with:
          files: ${{env.DLL_PATH }}
          dest: ${{env.ZIP_PATH }}

    #- name: ZIP build
    #  run: zip -r ${{ github.run_id }}.zip . -i AWSLambda
      
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
    
    - name: Upload to S3
      run: aws s3 cp ${{ github.run_id }}.zip s3://aws-task-bucket-lambdacode/${{ github.run_id }}.zip

    - name: Update lambda function code
      run: aws lambda update-function-code --function-name aws-task-lambda-kep --s3-bucket aws-task-bucket-lambdacode --s3-key ${{ github.run_id }}.zip
